// AUTO-GENERATED by qa/profile.mjs from qa-out/report.json (2026-07-03T07:18:41.506Z) — do not edit.
// Regenerate: node qa/run.mjs && node qa/profile.mjs
//
// cost: QA msPerFrame at 640x360 in headless Chrome — a RELATIVE load
// ranking, not a fullHD frame-time prediction. luma: meanLuma of the loud capture.

import type { SceneProfile } from "../engine/director.ts";

export const PROFILES: Record<string, SceneProfile> = {
  "02-reaction": { cost: 0.8, luma: 0.187 },
  "03-moire": { cost: 0, luma: 0.318 },
  "04-tunnel": { cost: 0.4, luma: 0.33 },
  "05-warp": { cost: 0.5, luma: 0.344 },
  "06-fluid": { cost: 2.1, luma: 0.288 },
  "07-boids": { cost: 0.8, luma: 0.047 },
  "16-slime": { cost: 1.5, luma: 0.198 },
  "20-mandelbulb": { cost: 3, luma: 0.171 },
  "21-menger": { cost: 1.2, luma: 0.157 },
  "22-terrain": { cost: 27.9, luma: 0.162 },
  "23-metaballs": { cost: 0.5, luma: 0.131 },
  "24-gyroid": { cost: 0.9, luma: 0.393 },
  "25-clouds": { cost: 24.6, luma: 0.672 },
  "29-apollonian": { cost: 3.4, luma: 0.385 },
  "30-mandelbrot": { cost: 0, luma: 0.185 },
  "31-plasma": { cost: 0, luma: 0.442 },
  "32-voronoi": { cost: 0, luma: 0.393 },
  "33-truchet": { cost: 0, luma: 0.182 },
  "34-hexgrid": { cost: 0, luma: 0.236 },
  "35-domainwarp": { cost: 0.1, luma: 0.388 },
  "36-caustics": { cost: 0, luma: 0.291 },
  "37-interference": { cost: 0, luma: 0.734 },
  "38-phyllotaxis": { cost: 0.4, luma: 0.083 },
  "39-gabor": { cost: 0, luma: 0.561 },
  "40-bars": { cost: 0.4, luma: 0.132 },
  "41-torus": { cost: 0.5, luma: 0.015 },
  "42-lissajous": { cost: 0.5, luma: 0.016 },
  "44-platonic": { cost: 0.5, luma: 0.019 },
  "50-matrix": { cost: 0, luma: 0.033 },
  "51-glitch": { cost: 0.2, luma: 0.527 },
  "52-oscilloscope": { cost: 0.5, luma: 0.165 },
  "62-aurora": { cost: 0, luma: 0.292 },
  "78-attractor": { cost: 0.4, luma: 0.093 },
  "81-fieldlines": { cost: 0.1, luma: 0.04 },
  "89-spectrogram": { cost: 0.1, luma: 0.208 },
  "90-radial_eq": { cost: 0, luma: 0.156 },
  "93-mandala": { cost: 0, luma: 0.363 },
  "94-cymatics": { cost: 0, luma: 0.106 },
  "95-rings": { cost: 0, luma: 0.522 },
};
