#!/usr/bin/env node
// Distills qa-out/report.json into src/scenes/profile.gen.ts: per-scene cost
// (msPerFrame) and luma (meanLuma) the live director uses to pick blend-hold
// pairs. Committed so production builds ship it; regenerate after a QA run:
//
//   node qa/run.mjs && node qa/profile.mjs
//
// Scenes that errored are omitted (no trustworthy metrics), which the director
// treats as "not hold-eligible".

import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const reportPath = join(here, "..", "qa-out", "report.json");
const outPath = join(here, "..", "src", "scenes", "profile.gen.ts");

const report = JSON.parse(readFileSync(reportPath, "utf8"));
const rows = report.scenes
  .filter((s) => s.status !== "error")
  .sort((a, b) => a.id.localeCompare(b.id))
  .map(
    (s) =>
      `  "${s.id}": { cost: ${Number(s.msPerFrame.toFixed(1))}, luma: ${Number(s.meanLuma.toFixed(3))} },`,
  )
  .join("\n");

writeFileSync(
  outPath,
  `// AUTO-GENERATED by qa/profile.mjs from qa-out/report.json (${report.ts}) — do not edit.
// Regenerate: node qa/run.mjs && node qa/profile.mjs
//
// cost: QA msPerFrame at ${report.w}x${report.h} in headless Chrome — a RELATIVE load
// ranking, not a fullHD frame-time prediction. luma: meanLuma of the loud capture.

import type { SceneProfile } from "../engine/director.ts";

export const PROFILES: Record<string, SceneProfile> = {
${rows}
};
`,
);
console.log(`[profile] ${report.scenes.length} scenes → ${outPath}`);
